### ISSUE TITLE
Add new Div field is too far left

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#109]
When you go into the pop-up to add a new Div and click on the "Add" text, the open-text field that opens displays way left of the title and other content dropdowns.

Also,  shouldn't there be a "cancel" button in the Add org pop-up? (Not for each field, but to cancel out of the whole thing?)

(BTW, otherwise, I really like how the org thing is working!)

**Comment by troddick** [comment]
The Close button accomplished the cancel.. closes the window. Each action (add a new Division, add a new Section) has an Add and Cancel button. Once you Add the Division or Section, it's done right then. The user can Cancel out of this action of adding a new one instead of hitting Add, or just close the popup before adding anything.
![image](https://cloud.githubusercontent.com/assets/1580076/14218097/c0aac6d6-f817-11e5-9e01-c5de00355e71.png)

Tonia
