### ISSUE TITLE
Site editing won't save, Cancel freezes DMS

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#166]
I started a new site, which went fine during save. I went back in to make some edits, and when I hit Save, nothing happened. I adjusted some values and tried again, and nothing happened. When I hit Cancel, the modal closed but the site list didn't load back up - I just got the gray screen with the spinning dots. When I tried to reload the page, I got the error below. When I went back to the project list and reloaded the project, it wouldn't let me access the Sites list again at all - it just stayed on whatever tab was already loaded.

In fact, I couldn't access ANY sites list from any project. I had to log out, clear my cache, and then things were back to normal. I redid the same process trying to edit a site in another project did the same thing (although I did see the green "site updated" alert pop up while it was frozen, so maybe it did something after all?).

![site_edit_cancel_error](https://cloud.githubusercontent.com/assets/16122136/17597278/a61fc8d8-5fba-11e6-9d6d-3de90fb9f716.png)

**Comment by troddick** [comment]
add loading gif to modal...

**Comment by jlbruce** [comment]
Hmm. As I started testing the site editing more, I'm getting the frozen Save issue again (not just the delay, but full on won't accept it and then freezes on cancel). Here are some of the errors I'm getting...

I can't remember if I was editing a new site or a duplicated site, but I changed info in almost every field. It bombed...
![site_edit_delay](https://cloud.githubusercontent.com/assets/16122136/17604571/06f94122-5fdc-11e6-932d-2b93d9d80231.png)

**Comment by jlbruce** [comment]
Then I duplicated a site and changed a bunch of things. It didn't bomb, but took a long time, and I noticed these errors. But it did let me continue...

![site_edit_delay_v2](https://cloud.githubusercontent.com/assets/16122136/17604605/2e9ca8fe-5fdc-11e6-8424-ab1085859cc1.png)

**Comment by jlbruce** [comment]
Then I started editing one field at a time and then trying to save. When I hit Resource Component, I got this error and it bombed out...

![edit_resource_component](https://cloud.githubusercontent.com/assets/16122136/17604636/44efa2f0-5fdc-11e6-8ef3-42c1fa52ad40.png)

**Comment by jlbruce** [comment]
Media was OK, but Sampling Frequency bombed...

![edit_sampling_frequency](https://cloud.githubusercontent.com/assets/16122136/17604702/94db57aa-5fdc-11e6-9cc1-68122d1947ac.png)

**Comment by jlbruce** [comment]
Parameters, too.... (let me know if you need me to test individual ones)

![edit_parameters](https://cloud.githubusercontent.com/assets/16122136/17604806/07490c06-5fdd-11e6-90bc-1c1bab73c326.png)

**Comment by troddick** [comment]
Ok. I think I got all of this resolved. The last few were all related to a single issue. Which, ironically I discovered before even getting that far down into your screenshots while I was testing something else. The duplicate repeaters.. I was only able to get that to happen one time yesterday and not again since then. I added some logic that should take care of that in case it crops up again. Your screenshot right after my comment about adding the loading gif is the same as the last few you added, so I think it's covered. 
Also, regarding speed.. I tried to increase the time it took to do stuff on the site page by adding a separate service within the client app that stores and gets the dropdowns (lakes, media, resources, etc) instead of getting those again each time a site is edited or created. I also addressed the order in which media, freq, and resources are showing up by adjusting the way the siglservices delivers those back after posting or editing (OrderBy .. property name). 
I'm going to leave this open to allow for another round of testing against these bugs to make sure they are all gone.

**Comment by jlbruce** [comment]
Seems to be working well! I was able to edit all three of the problematic fields without any errors, and except for one time, the response time was very speedy! But the new "I'm working" animation really helps tell the user to be patient. Well done!
