### ISSUE TITLE
MSE: lock activity during pop-up

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#187]
The MSE still lets you edit cells in the background underneath a pop-up, which can get annoying (and enter incorrect data). (I keep doing it because I want to hit Enter to clear the pop-up, which doesn't work, but it moves on to the next cell and can enter info if its a drop-down.)

Can we:
1. Prevent edits from being made while a pop-up is active?
2. Allow pop-ups to accept Enter if there's only one button (like the OK to clear the validation error pop-up)?

**Comment by troddick** [comment]
I have figured out a way to deselect a cell when a modal is being opened. That removes the ability to move around and edit the table with the modal open. 
I can not access the logic that allows the popup to accept Enter. I think it's because the table library is requesting it and it's too far removed from where i have that logic located.
So, I fixed the editing in the background, but can't add Enter = close modal when opened via the multiSiteEdit area.
