### ISSUE TITLE
"add new" has no editing capability after submitted

### ISSUE THREAD

**Issue by mbreitmun** [USGS-WiM/SiGLDMS#219]
I accidentally entered a truncated name within the "add new" feature for an Organization's Division. So, now I can choose from both the correct and incorrect names in the drop-down. Give users editing capability to the manual add-ins to avoid mix ups later?

**Comment by troddick** [comment]
I don't think we want to allow a data manager to edit the division added. What if that organization/division is being used by other projects by other data managers? I thought the plan was to allow the administrator to have this level of editing available to them in the Settings/Organizations section, which is still under development.

**Comment by jlbruce** [comment]
Agreed - since Publications are a shared resource, I don't want to let managers be able to edit or delete organizations. However, we could allow them to request an edit or deletion and link to the new SiGL email. How about this... at the bottom of the Add New pop-up (this same pop-up is used in both the Org and Contact sections, right?), we have a little message in italics that says: "Request that an organization name be edited or deleted", and the "Request" is a mailto: sigl@usgs.gov

**Comment by troddick** [comment]
Done.
